config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum:3, maximum:25 }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_userr ||= User.find(session[:user_id]) if session[:user_id]  
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:notice] = "Debes iniciar sesion para acceder a esta funcion"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  
  def index
    @message = Message.new
    @messages = Message.all
  end
end 

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    @message = Message.new(message_params)
 
    @message.user = current_user
    if @message.save
      # redirect_to root_path esto es lo que actualiza nuestra page
      ActionCable.server.broadcast 'chatroom_channel',
            {nuevo_mensaje: message_render(@message)}
    else 
      render 'new'
    end

  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:create, :new]
  def new
    
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Iniciado sesion con exito'
      redirect_to root_path
    else
      flash.now[:alert] = 'Hubo un error con tus credenciales'
      render 'new'
    end
  end

  # cuando cierras sesion se destruye la sesion
  def destroy
    session[:user_id] = nil
    flash[:success] = "Se ha cerrado la sesión"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'Ya has iniciado sesion'
      redirect_to root_path
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class='encabezado'>
    <h3 class="ui center aligned icon header">
    <i class="circular coffee icon blue"></i>
    Prueba escribiendo algo!
    </h3>
</div>

<div class="ui four column grid">
    <div class="one wide column"></div>
    <div class="ten wide column">
         <div class="ui card fluid raised card chat">
            <div class="content" id='mensajez'>
                <div class="ui feed" id='mensaje-contenedor'>
                    <%= render @messages %>
                </div>
            </div>

            <div class="extra content">
                <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, method: "POST", remote: true) do |f| %>

                    <div class="field">
                        <div class="ui blue fluid icon input">
                            <%= f.text_field :body, placeholder:'Escribe un mensaje...' %>
                            <%= f.button '<i class="bordered inverted blue icon edit"></i>'.html_safe %>
                            <%# <i class="bordered inverted blue icon edit"></i> %>
                        </div>
                    </div>
                <% end %>
                <%# <form class="ui reply form">
                    <div class="field">
                        <div class="ui blue fluid icon input">
                             <input type="text" placeholder="Escribe un mensaje...">
                            <i class="bordered inverted blue icon edit"></i>
                        </div>
                    </div>
                   
                </form> %>
            </div>

        </div>
    </div>

    <div class="four wide column">
        <div class="ui card fluid raised card chat">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="item">
                        Home
                    </a>
                    <a class="item active">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="one wide column"></div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type,msg| %>
    <div class="ui message <%= type == 'success' ? 'success' : 'negative' %>">
        <i class="close icon"></i>
        <div class="header">
            <%= msg %>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Sala", root_path, class:'item' %>
<a class="item">
    Mensajes
</a>
<div class="right menu">
    <div class="ui dropdown item">
        Cuenta <i class="dropdown icon"></i>
        <div class="menu">
            
            <% if logged_in? %>
                <%= link_to "Cerrar sesión", logout_path, class:"item" , method: :delete, data: { confirm: 'Estas seguro?' } %>
            <% else %>
                <%= link_to "Iniciar sesion", login_path, class:'item' %>
            <% end %>
            
        </div>
    </div>
    <% if !logged_in? %>
        <div class="item">
            <%= link_to "Registrate", login_path, class:'ui primary button' %>
            <%# <div class="ui primary button">Registrate</div> %>
        </div>   
    <% end %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MensajeaMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui huge menu inverted attached navv" id='navv'>
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>

    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>  
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em> <%= message.user.username %>: </em><%= message.body %>
        </div>
    </div> 
</div>